const MAPS = [
  {
    id:        'hawaii',
    label:     'Hawaii',
    sublabel:  'Tiki Bar',
    bg:        'assets/images/bg-tikibar.png',
    bgm:       'assets/audio/bgm.mp3',
    bgmVol:    0.35,
    itemsData: null, // filled after items.js loads (see bottom of this file)
  },
  {
    id:        'saigon',
    label:     'Saigon',
    sublabel:  'Pho House',
    bg:        'assets/images/bg-saigon.png',
    bgm:       'assets/audio/bgm-saigon.mp3',
    bgmVol:    0.30,
    itemsData: null, // filled below
    // Perspective-corrected tray boundary. Traced from hand-drawn magenta annotation,
    // then passed through unpersp() so walls land where items visually appear.
    // Generated by extract_hitbox.py — re-run to update.
    cornerWalls: [
      // top arc (left transition → peak → right transition)
      { x:   15, y:  172, len:   41, angle: -0.901 },
      { x:   57, y:  137, len:   70, angle: -0.574 },
      { x:  113, y:  110, len:   56, angle: -0.278 },
      { x:  163, y:   99, len:   48, angle: -0.147 },
      { x:  240, y:   98, len:  106, angle:  0.053 },
      { x:  322, y:  112, len:   61, angle:  0.373 },
      { x:  366, y:  133, len:   38, angle:  0.545 },
      { x:  395, y:  154, len:   34, angle:  0.727 },
      { x:  413, y:  187, len:   45, angle:  1.337 },
    ],
  },
  {
    id:       'kyoto',
    label:    'Kyoto',
    sublabel: 'Night Market',
    bg:       'assets/images/bg-kyoto.png',
    bgm:      'assets/audio/Lantern Alley.mp3',
    bgmVol:   0.35,
    itemsData: null,
  },
];

// Wire item sets after items.js has defined them.
MAPS[0].itemsData = HAWAII_ITEMS;
MAPS[1].itemsData = SAIGON_ITEMS;
MAPS[2].itemsData = KYOTO_ITEMS;

let ACTIVE_MAP = MAPS[0];
