// WHICH sound each map plays for each event.
//
// Voice ids come from SOUND_LIB in config/sounds.js (that file holds the actual
// synthesis). This file is pure data — the "wiring board".
//
// GENERATED by tools/sound-lab.html: pick a sound per map+event there, hit
// Save, and this whole file is rewritten. Hand-editing works too, but the lab
// will overwrite it, so make the change there instead if you can.
//
// `default` is the fallback: a map only lists an event when it wants something
// other than the default. So an empty map entry = "sounds like the house set",
// and adding a new event to `default` automatically applies everywhere.

const SOUND_MAP = {
  default: {
    merge:    'merge-glass',
    collide:  'collide-glass',
    coin:     'coin-blip',
    shoot:    'shoot-whoosh',
    gameOver: 'over-gently-down',
    best:     'best-brass-fanfare',
    levelUp:  'levelup-triad',
  },

  // Hawaii — Tiki Bar: the house set, unchanged.
  hawaii: {},

  // Saigon — Pho House: wooden bowls and broth.
  saigon: {
    merge:   'merge-bubble',
    collide: 'collide-wood-tok',
  },

  // Kyoto — Night Market: soft food, nothing with a hard edge.
  kyoto: {
    merge:   'merge-mochi',
    collide: 'collide-soft-food',
  },

  // Mage Tower: crystalline and shimmering.
  mage: {
    merge:   'merge-arcane',
    collide: 'collide-crystal',
  },

  // Plushie Factory: the softest profile in the game.
  teddy: {
    merge:   'merge-squeak',
    collide: 'collide-fabric',
  },

  // Melody Lane — music shop: everything is an instrument. The coin shower
  // climbs a pentatonic run so a big payout pours in as a harp cascade.
  melody: {
    merge:   'merge-pluck',
    collide: 'collide-hollow-body',
    coin:    'coin-pentatonic-run',
  },

  // Paris — Le Petit Café: china and pastry.
  paris: {
    merge:   'merge-china',
    collide: 'collide-pastry',
    coin:    'coin-bell',
  },

  // Farm — Sprout Valley: soil, wood and sprouting crops.
  farm: {
    merge:   'merge-sprout',
    collide: 'collide-dirt',
    coin:    'coin-xylophone',
  },
};
